// Vue/Router/src/App.vue
<template>
  <div>
      <div class="row">
        <div class="col-xs-offset-2 col-xs-8">
          <div class="page-header"><h2>Vue Router Demo</h2></div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-2 col-xs-offset-2">
          <div class="list-group">
            <router-link class="list-group-item" active-class="active" :to="{name:`about`}">About</router-link>
            <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="panel">
            <div class="panel-body">
              <router-view></router-view>
            </div>
          </div>
        </div>
      </div>
  </div>
</template>

<script>

export default {
  name: 'App',
  components: {
  }
}
</script>

<style>
* {
  color: #003366;
}

button {
  border: #5bc0de 1px solid;
  background-color: #00b3ee;
}

button:hover {
  border: #5bc0de 1px solid;
  background-color: #00aa00;
}

body {
  background-repeat: no-repeat;
  background-size: 1920px 960px;
  background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);
}
</style>

// React/react_router6/src/App.jsx
import React from 'react';
import {NavLink, Route, Routes} from "react-router-dom"
import About from "./pages/About"
import Home from "./pages/Home"

//react-router-dom V6
//该版本将Switch删除替换为Routes
//Route中的component属性替换为element={<xxx/>}
const App = () => {
    return (<div>
        <div className="row">
            <div className="col-xs-offset-2 col-xs-8">
                <div className="page-header"><h2>React Router Demo</h2></div>
            </div>
        </div>
        <div className="row">
            <div className="col-xs-2 col-xs-offset-2">
                <div className="list-group">
                    <NavLink className="list-group-item" to="/about">About</NavLink>
                    <NavLink className="list-group-item" to="/home">Home</NavLink>
                </div>
            </div>
            <div className="col-xs-6">
                <div className="panel">
                    <div className="panel-body">
                        <Routes>
                            <Route path={"/about"} element={<About/>}></Route>
                            <Route path={"/home"} element={<Home/>}></Route>
                        </Routes>
                    </div>
                </div>
            </div>
        </div>
    </div>);
};

export default App;
