// React/react-staging/src/component/List/index.jsx
import React, { Component } from "react";
import "./index.css";

export default class index extends Component {
  render() {
    const { users, isFirst, isLoading, err } = this.props;
    console.log();
    return (
      <div className="row">
        {isFirst ? (
          <h2 style={{ margin: "0 515px" }}>welcome!</h2>
        ) : isLoading ? (
          <h2 style={{ margin: "0 515px" }}>Loading...</h2>
        ) : err ? (
          <div style={{ margin: "0 441px", color: "red" }}>{err.message}</div>
        ) : (
          users.map((user) => {
            return (
              <div key={user.id} className="card">
                <a rel="noreferrer" href={user.html_url} target="_blank">
                  <img
                    alt="head_portrait"
                    src={user.avatar_url}
                    style={{ width: "100px" }}
                  />
                </a>
                <p className="card-text">{user.login}</p>
              </div>
            );
          })
        )}
      </div>
    );
  }
}

// Vue/Staging/src/components/List.vue
<template>
  <div class="row">
    <div class="card" v-for="user in info.users" :key="user.id">
      <a :href="user.html_url" target="_blank">
        <img
            :src="user.avatar_url"
            style="width: 100px"
        />
      </a>
      <p class="card-text">{{user.login}}</p>
    </div>
  </div>
</template>

<script>
export default {
  name: "List",
  data() {
    return {
      info: {
        users: []
      }
    }
  },
  mounted() {
    this.$bus.$on("getInfo",(info)=>{
      this.info.users = info
      console.log(info);
    })
  }
}
</script>

<style scoped>
.album {
  min-height: 50rem; /* Can be removed; just added for demo purposes */
  padding-top: 3rem;
  padding-bottom: 3rem;
  background-color: #f7f7f7;
}

.card {
  float: left;
  width: 33.333%;
  padding: .75rem;
  margin-bottom: 2rem;
  border: 1px solid #efefef;
  text-align: center;
}

.card > img {
  margin-bottom: .75rem;
  border-radius: 100px;
}

.card-text {
  font-size: 85%;
}
</style>
